
name: "Senses - Docs :: Release"

on: workflow_dispatch

jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.3'

      - name: Build
        run: |
          npm ci --quiet --no-progress
          npm run docs:build

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: ${{ secrets.SSH_USERNAME }}
          server: ${{ secrets.SSH_SERVER }}
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
 
          local_path: ./docs/.vuepress/dist/*
          remote_path: /var/www/docs.senses-smartmirror.com
          
          # sftp args
          args: '-o ConnectTimeout=5'
    
